export const APPLICATION_START = 'APPLICATION_START';

export const NAVIGATION_UP = 'NAVIGATION_UP';
export const NAVIGATION_DOWN = 'NAVIGATION_DOWN';
export const NAVIGATION_LEFT = 'NAVIGATION_LEFT';
export const NAVIGATION_RIGHT = 'NAVIGATION_RIGHT';